[package]
org = "isuruuy"
name = "lk_project"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="healthcare"
name="healthcare.fhir"
version="1.0.0"
repository="local"
